Tough kinematics
WPI-Humanoid-Robotics-Lab/tough pull request #32
Opened 2019-10-09 16:41 UTC by AshayAswale

This will give us the functionality to get the IK for manipulation, without using the MoveIt planners. Custom chain IK solver works, but cannot be executed as wholebody controller only accepts whole chains.

2019-10-09 19:33 UTC, ninja777 commented on tough_control/tough_kinematics/src/tough_kinematics.cpp
> +  result_traj.points.resize(1);
duplicate line

2019-10-09 19:35 UTC, ninja777 commented on tough_control/tough_kinematics/src/tough_kinematics.cpp
> +  KDL::Chain* current_chain = kdl_chains_[planning_group];
check if value exists in map before fetching it

2019-10-09 19:40 UTC, ninja777 commented on tough_control/tough_kinematics/src/tough_kinematics.cpp
> +  std::string first_frame = kdl_chains_[planning_group]->getSegment(0).getName();
verify value exists in map before accessing it

2019-10-09 19:43 UTC, ninja777 commented on tough_control/tough_kinematics/src/tough_kinematics.cpp
> +    ROS_ERROR("Planning group %s not initialized for ik solvers", planning_group);
return false

2019-10-09 19:44 UTC, ninja777 commented on tough_control/tough_kinematics/src/tough_kinematics.cpp
> +    int success = ik_solvers_[planning_group]->CartToJnt(kdl_initial_position, kdl_end_effector_pose, kdl_result);
check the need for this return value

2019-10-09 19:47 UTC, ninja777 commented on tough_control/tough_kinematics/src/tough_kinematics.cpp
> +void ToughKinematics::vectorToKDLJntArray(std::vector<double>& vec, KDL::JntArray& kdl_array)
function should be const
1st argument should be const

2019-10-09 19:47 UTC, ninja777 commented on tough_control/tough_kinematics/src/tough_kinematics.cpp
> +void ToughKinematics::KDLJntArrayToVector(KDL::JntArray& kdl_array, std::vector<double>& vec)
same as above

2019-10-09 19:49 UTC, ninja777 commented on tough_control/tough_kinematics/src/tough_kinematics.cpp
> +void ToughKinematics::poseToKDLFrame(const geometry_msgs::Pose& pose, KDL::Frame& frame)
function should be const

2019-10-09 19:50 UTC, ninja777 commented on tough_control/tough_kinematics/src/tough_kinematics.cpp
> +double ToughKinematics::get_planning_time()
function should be const

2019-10-10 16:28 UTC, AshayAswale commented on tough_control/tough_kinematics/src/tough_kinematics.cpp
> +void ToughKinematics::vectorToKDLJntArray(std::vector<double>& vec, KDL::JntArray& kdl_array)
`Eigen::Map<Eigen::VectorXd> data(ptr, vec.size());`
Cannot make 1st argument const, because no instance of contructor (const double, std::size_t) exists.

2019-10-10 20:39 UTC, ninja777 requested changes
minor changes required

2019-10-10 20:39 UTC, ninja777 commented on tough_control/tough_kinematics/include/tough_kinematics/tough_kinematics.h
> +  bool registerChain(const std::string& chain_start_parent, const std::string& chain_end, const std::string& group_name);
group_name -> chain_name

2019-10-10 20:39 UTC, ninja777 commented on tough_common/src/robot_description.cpp
> +  if(model_.links_.find(first_frame) != model_.links_.end())
return a single variable from if/else

2019-10-10 20:39 UTC, ninja777 commented on tough_control/tough_kinematics/include/tough_kinematics/tough_kinematics.h
> +  bool addCustomChain(const std::string& chain_start, const std::string& chain_end);
move to private

2019-10-10 20:39 UTC, ninja777 commented on tough_control/tough_kinematics/src/tough_kinematics.cpp
> +  for(auto i:ik_solvers_)
use `auto &`. more details [here](https://stackoverflow.com/questions/15927033/what-is-the-correct-way-of-using-c11s-range-based-for)

2019-10-28 15:36 UTC, merged